# -*- coding: utf-8 -*-
"""ScenarioDivider

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LJOyE7mAXAjS1N5LuBFF95-mP1P_2nGn

.datファイルをドラック＆ドロップで読み込んでください
"""

##ファイル名を入力！！！
##Enter the File Name
FileName = "X社　年次DATA９.xlsx"

##保存するときのファイル名を拡張子を省いて入力
##SaveFileName = "Test New Data File"

##全てのシナリオ区分を入力
ScenarioName = ["A", "B", "C", "D", "E"]

from IPython.utils import path
import openpyxl ##Excelを読み書きするため
import tqdm ##プログレスバーを表示するため
from openpyxl.chart import( ##Excelにグラフを描画するため
    ScatterChart,
    BarChart,
    Reference,
    Series,
)
import math

inputData = openpyxl.load_workbook(FileName) ##ファイルを開く Open File.

maxRow = inputData.active.max_row
maxColumn = inputData.active.max_column

"""配列は0から始まるが、Excelは1から始まることに注意！！"""
ScenarioData = [[0 for i in range(maxColumn)] for j in range(maxRow)]

reference = inputData.active.cell

for i in range(2, maxRow+1): ##1行目がタイトルのため2から始める
  for j in range(1, maxColumn+1):
    ScenarioData[i-2][j-1] = inputData.active.cell(row=i, column=j).value


##シナリオの区分の数だけシートを作成する
for i in range(len(ScenarioName)):
  inputData.create_sheet(ScenarioName[i])
  for j in range(1, maxColumn):
    inputData[ScenarioName[i]].cell(row=1, column=j).value = inputData['Sheet1'].cell(row=1, column=j).value

##シナリオごとにシートに分けて書き込む
for i in range(len(ScenarioName)):
  selectedSheet = inputData[ScenarioName[i]]
  writingLine = 2
  for j in range(len(ScenarioData)):
    # print(ScenarioData[3].scenario)
    if ScenarioData[j][0] == ScenarioName[i]: ##1列目がScenarioNameと一致したら
      for k in range(maxColumn):
        selectedSheet.cell(row=writingLine, column=k+1).value =  ScenarioData[j][k]#ScenarioData
      writingLine += 1



inputData.save("Edited_" + FileName) ##エクセルファイルを保存 Save Excel file

inputData.close() ##エクセルファイルを閉じる Close Excel file